/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.BaseDatos;
import java.util.Calendar;
import javax.swing.JFrame;

/**
 *
 * @author maxid
 */
public class VistaInicio extends javax.swing.JFrame {

    /**
     * Creates new form VistaInicio
     */
    public VistaInicio() {
        initComponents1();
        setResizable(false);
      
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void initComponents1() {
 
        GrupoBotones = new javax.swing.ButtonGroup();
        PanelInteriorAzul = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnArticulos = new javax.swing.JMenuItem();
        btnVentas = new javax.swing.JMenuItem();
        menuTemas = new javax.swing.JMenu();
        temaDark = new javax.swing.JMenuItem();
        temaLight = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
         setSize(1173, 650);
        PanelInteriorAzul.setBackground(new java.awt.Color(0, 51, 102));
        PanelInteriorAzul.setBorder(new javax.swing.border.MatteBorder(null));
        PanelInteriorAzul.setToolTipText("");
        PanelInteriorAzul.setRequestFocusEnabled(false);

        javax.swing.GroupLayout PanelInteriorAzulLayout = new javax.swing.GroupLayout(PanelInteriorAzul);
        PanelInteriorAzul.setLayout(PanelInteriorAzulLayout);
        PanelInteriorAzulLayout.setHorizontalGroup(
            PanelInteriorAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1540, Short.MAX_VALUE)
        );
        PanelInteriorAzulLayout.setVerticalGroup(
            PanelInteriorAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu1.setText("Archivo");

        btnArticulos.setText("Articulos");
        btnArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArticulosActionPerformed(evt);
            }
        });
        jMenu1.add(btnArticulos);

        btnVentas.setText("Ventas");
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        jMenu1.add(btnVentas);

        jMenuBar1.add(jMenu1);

        menuTemas.setText("Cuenta corriente");

        temaDark.setText("Clientes");
        temaDark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temaDarkActionPerformed(evt);
            }
        });
        menuTemas.add(temaDark);

        temaLight.setText("Proveedores");
        temaLight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temaLightActionPerformed(evt);
            }
        });
        menuTemas.add(temaLight);

        jMenuBar1.add(menuTemas);


        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelInteriorAzul, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelInteriorAzul)
        );

     
    }// </editor-fold>                        

    VistaControlStock inventario;
    VistaCtaCorrienteCliente ctaCorrienteCliente;
    VistaCtaCorrienteProveedor ctaCorrienteProveedor;
    vistaVentas ventas;
    
    private void btnArticulosActionPerformed(java.awt.event.ActionEvent evt) {                                             
             if (inventario == null) {
            inventario = new VistaControlStock();
            PanelInteriorAzul.add(inventario);
            PanelInteriorAzul.getDesktopManager().maximizeFrame(inventario);
            inventario.setVisible(true);
        } else if (JFrame.DISPOSE_ON_CLOSE == 2) {
            inventario = new VistaControlStock();

            PanelInteriorAzul.add(inventario);
            PanelInteriorAzul.getDesktopManager().maximizeFrame(inventario);
            inventario.setVisible(true);

        } else {
            PanelInteriorAzul.getDesktopManager().maximizeFrame(inventario);
        }
    }                                            

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {                                          
     if (ventas == null) {
            ventas = new vistaVentas();
            PanelInteriorAzul.add(ventas);
            PanelInteriorAzul.getDesktopManager().maximizeFrame(ventas);

            ventas.setVisible(true);
        } else {
            PanelInteriorAzul.getDesktopManager().maximizeFrame(ventas);
        }
    }                                         

    private void temaDarkActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
       if (ctaCorrienteCliente == null) {
            ctaCorrienteCliente = new VistaCtaCorrienteCliente();
            PanelInteriorAzul.add(ctaCorrienteCliente);
            PanelInteriorAzul.getDesktopManager().maximizeFrame(ctaCorrienteCliente);

            ctaCorrienteCliente.setVisible(true);
        } else {
            PanelInteriorAzul.getDesktopManager().maximizeFrame(ctaCorrienteCliente);
        }
    }       
                                            

    private void temaLightActionPerformed(java.awt.event.ActionEvent evt) {                                          
               if (ctaCorrienteProveedor == null) {
            ctaCorrienteProveedor = new VistaCtaCorrienteProveedor();
            PanelInteriorAzul.add(ctaCorrienteProveedor);
            PanelInteriorAzul.getDesktopManager().maximizeFrame(ctaCorrienteProveedor);

            ctaCorrienteProveedor.setVisible(true);
        } else {
            PanelInteriorAzul.getDesktopManager().maximizeFrame(ctaCorrienteProveedor);
        }
        
      
    }                                         
     
    

    
        

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup GrupoBotones;
    private javax.swing.JDesktopPane PanelInteriorAzul;
    private javax.swing.JMenuItem btnArticulos;
    private javax.swing.JMenuItem btnVentas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuTemas;
    private javax.swing.JMenuItem temaDark;
    private javax.swing.JMenuItem temaLight;
    // End of variables declaration                   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       
         */
        BaseDatos base = new BaseDatos();
        VistaInicio vista = new VistaInicio();
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaInicio().setVisible(true);
              /*  Calendar expireDate = Calendar.getInstance();

                expireDate.set(2020, 10, 11);

                if (Calendar.getInstance().after(expireDate)) {
     
                  System.exit(0);
}*/
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
